(define pow (#%vm-procedure (=> (dynamic-require "builtins" none) "pow") 2))
(define <= (#%vm-procedure (=> (dynamic-require "operator" none) "le") 2))
(define >= (#%vm-procedure (=> (dynamic-require "operator" none) "ge") 2))

(define eGFR 
    (lambda (age gender Scr CysC)
        (let ((A none)
              (B none)
              (C none)
              (D none)
              (E none))
            (cond ((equal? gender "female")
                   (set! E 0.963)
                   (set! A 0.7)
                   (set! C 0.8)
                   (if (<= Scr 0.7)
                       (set! B -0.219)
                       (set! B -0.544))
                   (if (<= CysC 0.8)
                       (set! D -0.323)
                       (set! D -0.778)))
                  (else 
                    (set! E 1)
                    (set! A 0.9)
                    (set! C 0.8)
                    (if (<= Scr 0.9)
                        (set! B -0.144)
                        (set! B -0.544))
                    (if (<= CysC 0.8)
                        (set! D -0.323)
                        (set! D -0.778))))
            (* 135 (pow (/ Scr A) B) (pow (/ CysC C) D) (pow 0.9961 age) E))))

(#%scm-procedure eGFR 4)